### ISSUE TITLE
Open sourced graphics conversion issue

### ISSUE THREAD

**Issue by Bertram25** [solarus-games/children-of-solarus#1]
@christopho 

This issue is about the WIP on converting the graphics to open sourced files.

I'll add there the precise list of files to redo, along with links to each ones.
This will greatly help me following the whole thing.

Not forgetting our hero: https://github.com/Bertram25/ChildenOfSolarus/issues/4

**Comment by Diarandor** [comment]
I am closing this issue since it is too general. Many of these things are already done or will be done "soon".
Better to open smaller and more specific issues.
