### ISSUE TITLE
Some free graphics and sounds

### ISSUE THREAD

**Issue by christopho** [solarus-games/children-of-solarus#25]
Here are some links to free graphics and sounds gathered by zutokaza here: http://forum.solarus-games.org/index.php/topic,401.15.html
It can probably help.

I found some CC-By 3.0 Sprites we can use in the book.
http://opengameart.org/content/antifareas-rpg-sprite-set-1-enlarged-w-transparent-background-fixed

http://opengameart.org/content/18x20-characters-walkattackcast-spritesheet

CC0 Public doman Explosions, weapons, tileset, items:
http://opengameart.org/content/explosion-animations

http://opengameart.org/content/16x16-rpg-items

http://opengameart.org/content/old-frogatto-tile-art

http://opengameart.org/content/old-frogatto-tiles-pt2

Menu CC- BY
http://opengameart.org/content/fantasy-ui-elements-by-ravenmore

GUI 1: CC- BY - SA
http://opengameart.org/content/denzis-gui-artwork

Other GUI and UI

http://goo.gl/eWFZmT

http://goo.gl/bFYYJR

http://goo.gl/Mkru1b

Faces CC- BY and SA (CC0 as well)
http://opengameart.org/art-search-advanced?field_art_tags_tid=anime

Patterns for the book (Covers and pages)
http://goo.gl/B0Wjvy

Music CC- By and CC- SA

http://opengameart.org/content/8bit-thingy

http://opengameart.org/content/music-2

http://opengameart.org/content/randomtheme

Other music:
http://opengameart.org/art-search-advanced?field_art_tags_tid=chiptune

Sound effects:
http://opengameart.org/art-search-advanced?keys=&field_art_licenses_tid%5B%5D=2&field_art_licenses_tid%5B%5D=3&field_art_tags_tid_op=and&field_art_tags_tid=sfx&name=&sort_by=created&sort_order=DESC&items_per_page=24&Collection=

We can find some more as we go on with the chapters.

**Comment by Bertram25** [comment]
Arf, that project definitely needs love. ;)

**Comment by christopho** [comment]
A full collection of othogonal tilesets suggested by zutokaza:
http://opengameart.org/content/best-orthogonal-rectangular-tilesets-for-tilemaps

**Comment by zutokaza** [comment]
How does this project work? Does it just collect links or will it gather resources in the folders with appropriate credit?

Here are more.

He has lots of music, but from the 16 I checked they are all CC-BY.
http://opengameart.org/users/horrorpen

More free music: CC-By-SA
http://opengameart.org/users/remaxim

Some weapons and Items CC-BY:
http://opengameart.org/content/32x32-icons-flare-compatible

**Comment by christopho** [comment]
Anyone can contribute, by replacing sprites, tilesets, musics and sounds by free ones. Credits are given in licence.txt.
Collecting links is a good start, but other issues are tracking the work on converting graphics and sounds.

**Comment by zutokaza** [comment]
I have AnyVideoConverter (Works with audio too. .ogg, flac, etc) and I can compress the png images with no quality loss using Pngyu. I could help with compression and converting. I am currently scouting for free resources for my game(s) and I always come across tons of music. I have collected over 2 GB in the last 2 days, but I will be revising those for neat credit list organization. I have separate crediting documents all over in different folders.

**Comment by zutokaza** [comment]
I found a good public domain asset set CC0. The license is in the small archive.
http://www.kenney.nl/assets/roguelike-rpg-pack

**Comment by zutokaza** [comment]
I found a 2 GB package of free music. it is CC-BY 3.0. The top says royalty free in the title, but it says it is under creative commons at the bottom of the home page. There is no previews and only a torrent that has been updated 22 days ago.
http://www.nosoapradio.us/

**Comment by zutokaza** [comment]
This site has a lot of free music, but there is a lot of non-commercial use too. It is easy to see what the license is from the icon/image mark.
https://www.freesound.org/browse/tags/sci-fi/

For instance,
This pack is public domain.
http://freesound.org/people/Kastenfrosch/packs/10069/?page=2#sound

Here is another site:
http://soundbible.com/tags-game.html

Another huge pack made by Aaron. CC-BY
http://forums.rpgmakerweb.com/index.php?/topic/926-rpg-music-pack-free-commercial-use/

Public Domain Sound pack:
http://opengameart.org/content/rpg-sound-pack

I saw other free sound effect sites, but they seems totally unreliable (I saw a Dragon Ball Z Kai theme in there). There are many free legit ones, but some like the Dragon Ball Z one is obviously not free. Here are the sites. http://www.freesfx.co.uk/

http://www.hongkiat.com/blog/55-great-websites-to-download-free-sound-effects/

I will mostly be adding links from Opengameart.org from now on unless I notice a good site.

**Comment by zutokaza** [comment]
Christopho.....should I upload and send you a link to the 500 free music files? (1.1 GB)

**Comment by zutokaza** [comment]
Here is another set of open source CC-BY 3.0  music made by Snabisch. I included all the credit file and converted the original formats to OGG. The original formats are included, but they are quite large.
https://drive.google.com/folderview?id=0B3ogMy4W2CKeSThHblhTN3EteTQ&usp=sharing

**Comment by zutokaza** [comment]
I have been going through the list for the book and have converted the audio to OGG (Original formats included. Also, compressed the png files with pngyu and the difference is not noticeable, but I have included the original files too. I did not go through all the list, but will mark where I collected from.
https://drive.google.com/folderview?id=0B3ogMy4W2CKeS3RCTWtLVTRNeXc&usp=sharing

I have collected a hundred links to tilesets and a few sprites. I will post those later and start going through them.

-----------------------------------------------------------------------------------------------------------------------

I found some CC-By 3.0 Sprites we can use in the book. (Collected)
http://opengameart.org/content/antifareas-rpg-sprite-set-1-enlarged-w-transparent-background-fixed

http://opengameart.org/content/18x20-characters-walkattackcast-spritesheet

CC0 Public doman Explosions, weapons, tileset, items: (Collected)
http://opengameart.org/content/explosion-animations

http://opengameart.org/content/16x16-rpg-items

http://opengameart.org/content/old-frogatto-tile-art

http://opengameart.org/content/old-frogatto-tiles-pt2

Menu CC- BY (Collected)
http://opengameart.org/content/fantasy-ui-elements-by-ravenmore

GUI 1: CC- BY - SA (Collected)
http://opengameart.org/content/denzis-gui-artwork

Other GUI and UI (Did not collected)

http://goo.gl/eWFZmT

http://goo.gl/bFYYJR

http://goo.gl/Mkru1b

Faces CC- BY and SA (CC0 as well) - (Did not collected)
http://opengameart.org/art-search-advanced?field_art_tags_tid=anime

Patterns for the book (Covers and pages) - (Did not collect)
http://goo.gl/B0Wjvy

Music CC- By and CC- SA (Collected)

http://opengameart.org/content/8bit-thingy

http://opengameart.org/content/music-2

http://opengameart.org/content/randomtheme

Other music: (Did not collected yet)
http://opengameart.org/art-search-advanced?field_art_tags_tid=chiptune

Sound effects: (Did not  collect yet)
http://opengameart.org/art-search-advanced?keys=&field_art_licenses_tid%5B%5D=2&field_art_licenses_tid%5B%5D=3&field_art_tags_tid_op=and&field_art_tags_tid=sfx&name=&sort_by=created&sort_order=DESC&items_per_page=24&Collection=

**Comment by zutokaza** [comment]
Here is more CC-BY 3.0 music I collected a while back. I added the originals and the OGG.
https://drive.google.com/folderview?id=0B3ogMy4W2CKeQklNX1kxSnRHS2c&usp=sharing

Also, here are the hundred links.

http://opengameart.org/content/recolor-all-the-items

http://opengameart.org/art-search-advanced?keys=Tileset&field_art_type_tid%5B%5D=9&field_art_type_tid%5B%5D=10&field_art_type_tid%5B%5D=7273&field_art_type_tid%5B%5D=14&field_art_type_tid%5B%5D=12&field_art_type_tid%5B%5D=13&field_art_type_tid%5B%5D=11&field_art_licenses_tid%5B%5D=2&field_art_licenses_tid%5B%5D=3&field_art_licenses_tid%5B%5D=6&field_art_licenses_tid%5B%5D=5&field_art_licenses_tid%5B%5D=10310&field_art_licenses_tid%5B%5D=4&field_art_licenses_tid%5B%5D=8&field_art_licenses_tid%5B%5D=7&field_art_tags_tid_op=and&field_art_tags_tid=&name=&sort_by=created&sort_order=DESC&items_per_page=24&Collection=


http://opengameart.org/content/snow-tileset-for-rpgs

http://opengameart.org/content/the-field-of-the-floating-islands

http://opengameart.org/content/forest-tileset-for-rpgs

http://opengameart.org/content/cave-tileset-for-rpgs

http://opengameart.org/content/some-1616-rpg-tiles

http://opengameart.org/content/the-revolution-snow

http://opengameart.org/content/limestone-tileset-32x32

http://opengameart.org/content/the-revolution-sprites

http://opengameart.org/content/the-revolution-grasslands

http://opengameart.org/content/tiled-terrains

http://opengameart.org/content/side-blaster-gfx-m484-games

http://opengameart.org/content/unfinished-dungeon-tileset

http://opengameart.org/content/32x32-tile-pixel-art-tilesheet

http://opengameart.org/content/simple-2d-cave-tileset

http://opengameart.org/content/stone-works

http://opengameart.org/content/2d-modified-dark-forest-tileset

http://opengameart.org/content/dawnlike-16x16-universal-rogue-like-tileset-v181

http://opengameart.org/content/dawnlike-16x16-universal-rogue-like-tileset-v181

http://opengameart.org/content/dungeon-tileset

http://opengameart.org/content/64x64-isometric-roguelike-tiles

http://opengameart.org/content/colored-16x16-fantasy-tileset

http://opengameart.org/content/lpc-house-insides

http://opengameart.org/content/minimalistic-rpg-game-assets-2-back-and-stronger

http://opengameart.org/content/tables-and-stools

http://opengameart.org/content/mushroom-houses

http://opengameart.org/content/zwischenwelt-tileset

http://opengameart.org/content/ground-tileset-grass-sand

http://opengameart.org/content/two-dungeon-wall-tilesets

http://opengameart.org/content/palmjungle-trees-for-32x32-tileset

http://opengameart.org/content/tileset

http://opengameart.org/content/pseudo-nes-tileset

http://opengameart.org/content/16x16-minimalistic-rpg-spritessome-tiles

http://opengameart.org/content/yellowish-green-grass-tileset

http://opengameart.org/content/dirt-grass-rock-platformer-terrain-32x32

http://opengameart.org/content/blowhard-2-blow-harder

http://opengameart.org/content/8x8-tileset-by-soundlust

http://opengameart.org/content/old-frogatto-tile-art-3

http://opengameart.org/content/lpc-plant-repack

http://opengameart.org/content/16x16-fantasy-tileset

http://opengameart.org/content/tiny-16-basic

http://opengameart.org/content/top-down-simple-tile-sets

http://opengameart.org/content/house-tileset-blackguard

http://opengameart.org/content/snowy-tiles

http://opengameart.org/content/lots-of-hyptosis-tiles-organized

http://opengameart.org/content/lpc-style-wood-bridges-and-steel-flooring

http://opengameart.org/forumtopic/universal-lpc-sprite-sheet

http://opengameart.org/content/rpg-tiles-cobble-stone-paths-town-objects

http://opengameart.org/content/rpg-tiles-cobble-stone-paths-town-objects

http://opengameart.org/content/16x16-town-remix

http://opengameart.org/content/32x32-fantasy-tileset

http://opengameart.org/content/cobblestone-tileset

http://opengameart.org/content/lpc-tile-atlas2

http://opengameart.org/content/camp-fire-animation-for-rpgs-finished

http://opengameart.org/content/top-down-grass-beach-and-water-tileset

http://opengameart.org/content/tree-variations-from-jetrels-wood-tileset

http://opengameart.org/content/lpc-tile-atlas

http://opengameart.org/content/2d-lost-garden-tileset-transition-to-jetrels-wood-tileset

http://opengameart.org/content/2d-lost-garden-zelda-style-tiles-winter-theme-with-additions

http://opengameart.org/content/dungeon-crawl-32x32-tiles

http://opengameart.org/content/lpc-obok-and-gossip-art-additions-and-modifications

http://opengameart.org/content/mage-city-arcanos

http://opengameart.org/content/lpc-colorful-sand-deep-water

http://opengameart.org/content/lpc-farming-tilesets-magic-animations-and-ui-elements

http://opengameart.org/content/lpc-a-shootem-up-complete-graphic-kit

http://opengameart.org/content/16x16-forest-tiles

http://opengameart.org/content/whispers-of-avalon-animated-ocean-tileset

http://opengameart.org/content/16x16-jrpg-tilesets-enlarged-2x

http://opengameart.org/content/the-revolution-grasslands

http://opengameart.org/content/16x16-snowy-town-tiles

http://opengameart.org/content/arctic-tileset

http://opengameart.org/content/rpg-indoor-tileset-expansion-1

http://opengameart.org/content/xooxers-grass-2-ground-tileset

http://opengameart.org/content/whispers-of-avalon-desert-tileset

http://opengameart.org/content/16x18-zombie-characters-templates-extra-template

http://opengameart.org/content/the-mana-worldforest-tileset

http://opengameart.org/content/objects-for-16x16-tilesets

http://opengameart.org/content/cave-tileset-0

http://opengameart.org/content/32x32-and-16x16-rpg-tiles-forest-and-some-interior-tiles

http://opengameart.org/content/16x16-indoor-rpg-tileset-the-baseline

http://opengameart.org/content/basic-bricks

http://opengameart.org/content/treasure-chests-32x32-and-16x16

http://opengameart.org/content/rpg-item-set

http://opengameart.org/content/modified-32x32-treasure-chest

http://opengameart.org/content/pagesofadventure-grass-tileset

http://opengameart.org/content/grass

http://opengameart.org/content/gnarled-tree

http://opengameart.org/content/twelve-more-characters-3-free-characters-and-a-child-template

http://opengameart.org/content/twelve-16x18-rpg-character-sprites-including-npcs-and-elementals

http://opengameart.org/content/tileset-1bit-color

http://opengameart.org/content/twelve-16x18-rpg-sprites-plus-base

http://opengameart.org/content/twelve-more-16x18-rpg-character-sprites

http://opengameart.org/content/old-frogatto-tile-art

http://opengameart.org/content/whispers-of-avalon-grassland-tileset

http://opengameart.org/content/oga-community-tileset-nature

http://opengameart.org/content/overworld-rpg-tileset

http://opengameart.org/content/town-tiles

http://opengameart.org/content/forest-tiles

http://opengameart.org/content/planetcute-chest-openpng

http://opengameart.org/content/2d-circle-graphic-archive-treegif

http://opengameart.org/content/xorgramana-pngs-wall1png

**Comment by zutokaza** [comment]
I found a small collection of Public Domain CC0 music. They were already in an open source OGG format. I included the license in the file.
https://drive.google.com/folderview?id=0B3ogMy4W2CKeX2tsN3JrdTZudDQ&usp=sharing

**Comment by zutokaza** [comment]
Here is HorrorPen's Favorites: (Might want to look through it)
http://opengameart.org/user/1551/favorites

HorrorPen's music is CC-BY 3.0. I have already collected it and will be converting it now.

**Comment by zutokaza** [comment]
I have been looking through http://untamed.wild-refuge.net/rmxpresources.php?characters.
Most of the characters are legit and I removed 3 that were close to the RPG MAKER XP RTP. I am not sure if there is anymore (Tilesets, etc), but it will be a work in progress for http://untamed.wild-refuge.net/rmxpresources.php?characters.

Here is the link to it. They will be a great addition if the RPG MAKER XP edits are removed. I will as the RPG maker XP communities to help remove the edits. I added the link to the XP RTP to help compare and remove. I have not added the free tilesets from the site and only sprites.
https://drive.google.com/folderview?id=0B3ogMy4W2CKecGNzbVlLbFhBdjA&usp=sharing

**Comment by zutokaza** [comment]
A bunch of CC-BY-SA 3.0 assets:
http://lpc.opengameart.org/static/lpc-style-guide/assets.html

**Comment by zutokaza** [comment]
GUI

http://opengameart.org/content/general-gui 

http://opengameart.org/content/user-interface

**Comment by zutokaza** [comment]
12 or so free art packs:
http://www.as3gamegears.com/category/assets/

**Comment by zutokaza** [comment]
The links above can direct you to more great free tilesets. You can look in the OpenGameArt.org users favourites/favorites and collections because it's easier to find a lot of good free art that way. It's harder with searching keywords for me.

I also have a collection I downloaded and can give a link to that if you want it, but you guys/girls might want to download it yourselves, so I just deleted my old comments and organized the links into three comments. That way it does not look like a total mess.

I will add more of what I find, but for now there won't be much updates.

**Comment by zutokaza** [comment]
It seems the search tags changed in open game art. I replaced them, but 99% of the links are okay because they are actual URL and not a search result URL.

**Comment by zutokaza** [comment]
Note:
The majority of stuff in these links here I collected and posted on the forum.

**Comment by christopho** [comment]
I checked the first two character sprite sheets
(http://opengameart.org/content/antifareas-rpg-sprite-set-1-enlarged-w-transparent-background-fixed and http://opengameart.org/content/18x20-characters-walkattackcast-spritesheet). They look really great, but they are too small (18x20), they don't fit well with the main characters we have.

**Comment by christopho** [comment]
18x20 characters really don't fit, even with a hero of the size of Zelda A Link to the Past:
![too_small_npc](https://github-cloud.s3.amazonaws.com/assets/411718/10565007/2ee5f36a-75c7-11e5-93e0-0b7ca840a54c.png)
![too_small_npc_2](https://github-cloud.s3.amazonaws.com/assets/411718/10565029/a12c81fa-75c7-11e5-9691-e75adfe273ac.png)

**Comment by christopho** [comment]
Maybe we could use 18x20 sprites for the hero and all characters of the game?

**Comment by zutokaza** [comment]
I sent a private message to you on the forum with a link to the resource collection. I had to remove the post due to strange traffic that could disable my email. It has happened to me with dropbox before.....darn spammers.

**Comment by Diarandor** [comment]
As many of you already know, I am working on original graphics for the hero and also lots of sounds. When finished, they could be used to replace them here. (Some of them are already included in the sample quest, but they are still unfinished.)

However, they are not free as in freedom (they are free as in free beer), and they will have the license CC BY-NC-SA 4.0 (which is a non-commercial license); I just wanted to point this out.

**Comment by Nate-Devv** [comment]
Free as in free beer is better than Nintendo owned that could potentially shut the entire project down, at least in my mind.

**Comment by Diarandor** [comment]
All my art is now free as in freedom. All my pixel art is now officially CC-BY-SA, and can be found here:
http://diarandor.deviantart.com

Most of the inventory items are done, and the remaining work can be found here:
https://github.com/Diarandor/repository/issues/58

**Comment by Zefk** [comment]
That is great news Diarandor! I will check out your works.

**Comment by Diarandor** [comment]
Hi @Zefk: although all my work is now free and therefore you can do whatever you want (only credit is needed), I would like that my art is not mixed with other authors' art whenever it is possible, because that is bad to give credit properly to each author (especially if someone makes the opposite  and splits an art compilation in several pieces each one belonging to only one author, which means that all the authors will be given credit for the work of only one). Doing compilations is not really necessary for item sprites since each sprite can have each animation in a different image file).

Anyway that is only my opinion and you are free to make compilations, mixing my art with other authors' free work.

You can also find all this art in the sample quest of the development version of Solarus (with most of the "dat" files for the sprites), so there is no need in downloading each file separately from my deviantart. The remaining sprites for items and the hero will be finished before next July month, and the same goes for the remaining ogg sounds.

I also became officially a member of the Solarus team, so if you or anyone want to support this pixel-art work (or Christopho's work, which is by far much more important), donations should be done in the official Solarus website.

**Comment by Zefk** [comment]
@Diarandor I will respect your wishes and not mix or merge your graphics with others art, but I might edit or mod some of your work and keep it on separate image files if that it is okay with you. You will always be notified and a copy of the edit will be sent to you.

Congratulations on becoming part of the Solarus Team!

**Comment by Diarandor** [comment]
Thanks a lot! There is no need to notify or send me your modifications.

I intend to replace all ALTTP graphics, including tilesets. It is gonna take 2 years aproximately, at most. This summer I will work on the NPCs graphics. I will notify of the news from time to time on the forum.

**Comment by Zefk** [comment]
I found some message boxes in my resource collection. I noticed that this project already has a [dialog box](https://github.com/solarus-games/children-of-solarus/blob/master/data/sprites/hud/dialog_box.png), but maybe someone would like to check them out anyway. I attached the zip with the license. They are CC-BY 3.0 license.


![10_basic_message_boxes_by_Charles_Gabriel.png](https://s28.postimg.org/v263eb0fx/10_basic_message_boxes_by_Charles_Gabriel.png)

[Basic Message Boxes.zip](https://github.com/solarus-games/children-of-solarus/files/697589/Basic.Message.Boxes.zip)

**Comment by Diarandor** [comment]
I'm closing this issue since it is too general and not necessary anymore.
For particular things, new issues can be opened.
