### ISSUE TITLE
Change the origin point for the sprites of Eldran

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/children-of-solarus#32]
When pushing a wall in the down direction (the direction of the hero is 3), there are two pixels of separation between Eldran and the wall. I think it would be better to shift the origin of the sprites one or two pixels to make him closer to the wall. The same has to be done with all his sprites.

EDIT: the same has to be done with all weapon sprites.

**Comment by Diarandor** [comment]
@christopho: You can assign me to do the issue if you want.

**Comment by christopho** [comment]
@Diarandor: i just gave you write access to this repository, you can make assignments now.

**Comment by Diarandor** [comment]
Thanks!

**Comment by Diarandor** [comment]
This is issue is already done (or being done) for the new (remastered) sprites of Eldran.
No need for this issue.
