### ISSUE TITLE
Add a "hint" for first diagonal jumper?

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/children-of-solarus#33]
I was thinking that we could add a hint for the first diagonal jumper (you probably already know which one I am refering to), if you like the idea and agree. What do you think about this?

Some players (including myself) have been stuck in this part since this was not completely obvious. The hint could be an animal (maybe a cat) jumping in that jumper when you get close to it; the player should then guess that he/she can jump there too.

I am against using straightforward hints like wooden signs, whenever it is possible, because otherwise the player may think we are treating him/her as a kid.

**Comment by Renkineko** [comment]
There is already a hint with the leaves path, but i agree it's not very obvious.

**Comment by Diarandor** [comment]
I don't know if it will be clear with the grounds of the new tileset (I still have to draw these ground tiles), so it may be a good idea to add the animal hint too, but only if @christopho agrees.

**Comment by christopho** [comment]
Maybe we will just get rid of this particular puzzle, this diagonal jump was not looking normal at all.

**Comment by Diarandor** [comment]
@christopho: After your last mapping video streaming, I think we can already close this issue.
Don't you agree?
