### ISSUE TITLE
Use custom jump instead of built-in jump

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/children-of-solarus#40]
We had already decided not to use a custom jump that allows to control the hero movement during the jump because this would break many puzzles of the game (this includes, mainly, puzzles with conveyor belts, and crossroads involving bad grounds). However, I found an easy solution that would allow to keep the same puzzles without "breaking" them, and so I would like to suggest to add the custom jump. Note that the custom jump will make the game cooler, so all of this is worth it.

The solution I propose is the following. We can create a special type of "magical" tile (custom entity?) that forces the hero to jump in the facing direction if he is above the tile, it is just as simple as this. These special tiles could have the following design: just a cross with a circle in the middle, and when the hero jumps, the circle in the middle could illuminate (and flicker) for a very short time. Since the player will notice this flickering, he will easily deduce that the special tiles are responsible of that restricted behavior of the jump in these tiles. We just need to put these tiles in the places where we really want the hero to jump in the facing direction, that is, where the puzzles "require" this condition. There may be other places around hole grounds (or other types of bad grounds) where we need to put these tiles, so we need to be careful to not forget about this.

Other cool (but not original) ideas for the game with the custom jump are:
-Flying pickables, like the ones in Link's Awakening (hearts, rupees, etc).
-Flying enemies (like bats) that can only be hurt if we attack them with the sword during the jump (this is very easy to do, since we can shift all the sprites, including the sword sprite, and actually this was already tested by me some time ago and works correctly).

@christopho Do you agree that we should use the custom jump instead of the built-in one?
I am sure that this time I will convince you!!! 😄

**Comment by christopho** [comment]
But a special tile that blocks the jump liberty is too artificial. Blocking a feature to make a puzzle work is bad design :P
Maybe we can put two variants of the feather instead? The first one that jumps straight ahead, and the better one later in the game?

**Comment by Diarandor** [comment]
You are right, special tiles are too artificial... even more than conveyor belts. So your solution is probably better. The first feather (built-in jump) could then be a spring instead, and the second one (custom jump) a lightness feather.

In any case, it is very convenient to add the custom jump to the game, so that players will realize that Solarus does not have so many limitations (we have to give a good impression in our first game).

**Comment by Diarandor** [comment]
The custom jump script was already done.

**Comment by vlag** [comment]
Just for my curiosity, is it possible to jump while running with your custom jump ?

**Comment by Diarandor** [comment]
Good question. With custom boots yes, and I tested it. With the built-in boots I have not tested this, but it should be doable, at least by adding some code.
